"""Plain-language explanation templates keyed by (category, current_stage).

Used by the fallback path so a demo without an OpenAI key still reads as a
polished, specific product rather than a generic status string.
"""

from app.models.enums import ServiceCategory

# Each entry: whats_happening, current_blocker, who_needs_to_act, what_you_should_do, next_step_label, then_step_label
TEMPLATES: dict[ServiceCategory, dict[str, dict[str, str]]] = {
    ServiceCategory.STREETLIGHT: {
        "Submitted": {
            "whats_happening": "Your report has been received and is being assigned to the local engineering team.",
            "current_blocker": "Assignment to a field engineer is pending.",
            "who_needs_to_act": "Municipal Engineering Department",
            "what_you_should_do": "No action is required from you right now.",
            "next_step_label": "Assigned",
            "then_step_label": "Site Inspection",
        },
        "Assigned": {
            "whats_happening": "Your complaint has been assigned to the municipal engineering team.",
            "current_blocker": "A site inspection has not yet been scheduled.",
            "who_needs_to_act": "Junior Engineer, Ward team",
            "what_you_should_do": "No action is required from you right now.",
            "next_step_label": "Site Inspection",
            "then_step_label": "Repair",
        },
        "Site Inspection": {
            "whats_happening": "Your complaint has been assigned to the responsible municipal team. Site inspection is pending.",
            "current_blocker": "Site inspection has not been completed.",
            "who_needs_to_act": "Junior Engineer, Ward team",
            "what_you_should_do": "No action is required from you right now. If it's urgent, you can escalate.",
            "next_step_label": "Repair",
            "then_step_label": "Citizen Verification",
        },
        "Repair": {
            "whats_happening": "The fault has been confirmed and a repair order has been issued.",
            "current_blocker": "Repair work is in progress or awaiting a maintenance crew.",
            "who_needs_to_act": "Municipal Maintenance Crew",
            "what_you_should_do": "No action is required from you right now.",
            "next_step_label": "Citizen Verification",
            "then_step_label": "Case Closed",
        },
        "Citizen Verification": {
            "whats_happening": "The authority has marked this as resolved. We're waiting for you to confirm it's actually fixed.",
            "current_blocker": "Your confirmation is the only remaining step.",
            "who_needs_to_act": "You",
            "what_you_should_do": "Check the streetlight and tell us if it's actually working now.",
            "next_step_label": "Case Closed",
            "then_step_label": "-",
        },
    },
    ServiceCategory.POTHOLE: {
        "Submitted": {
            "whats_happening": "Your report has been received and is being routed to the roads team.",
            "current_blocker": "Assignment to a field engineer is pending.",
            "who_needs_to_act": "Municipal Roads Department",
            "what_you_should_do": "No action is required from you right now.",
            "next_step_label": "Assigned",
            "then_step_label": "Site Inspection",
        },
        "Assigned": {
            "whats_happening": "Your complaint has been assigned to the roads engineering team.",
            "current_blocker": "A site inspection has not yet been scheduled.",
            "who_needs_to_act": "Junior Engineer, Ward team",
            "what_you_should_do": "No action is required from you right now.",
            "next_step_label": "Site Inspection",
            "then_step_label": "Repair",
        },
        "Site Inspection": {
            "whats_happening": "An engineer is expected to inspect the road damage before repair work is ordered.",
            "current_blocker": "Site inspection has not been completed.",
            "who_needs_to_act": "Junior Engineer, Ward team",
            "what_you_should_do": "No action is required from you right now.",
            "next_step_label": "Repair",
            "then_step_label": "Citizen Verification",
        },
        "Repair": {
            "whats_happening": "The road damage has been confirmed and a repair order has been issued.",
            "current_blocker": "Repair work is in progress or awaiting materials/crew.",
            "who_needs_to_act": "Municipal Maintenance Crew",
            "what_you_should_do": "No action is required from you right now.",
            "next_step_label": "Citizen Verification",
            "then_step_label": "Case Closed",
        },
        "Citizen Verification": {
            "whats_happening": "The authority has marked this as resolved. We're waiting for you to confirm it's actually fixed.",
            "current_blocker": "Your confirmation is the only remaining step.",
            "who_needs_to_act": "You",
            "what_you_should_do": "Check the road and tell us if the repair actually happened.",
            "next_step_label": "Case Closed",
            "then_step_label": "-",
        },
    },
    ServiceCategory.WATER_SUPPLY: {
        "Submitted": {
            "whats_happening": "Your report has been received by the water board.",
            "current_blocker": "Assignment to a field team is pending.",
            "who_needs_to_act": "Municipal Water Board",
            "what_you_should_do": "No action is required from you right now.",
            "next_step_label": "Assigned",
            "then_step_label": "Field Inspection",
        },
        "Assigned": {
            "whats_happening": "Your complaint has been assigned to the water distribution team.",
            "current_blocker": "A field inspection has not yet been scheduled.",
            "who_needs_to_act": "Assistant Engineer, Water Board",
            "what_you_should_do": "No action is required from you right now.",
            "next_step_label": "Field Inspection",
            "then_step_label": "Repair",
        },
        "Field Inspection": {
            "whats_happening": "A team is expected to inspect the supply line or source before repair work is ordered.",
            "current_blocker": "Field inspection has not been completed.",
            "who_needs_to_act": "Assistant Engineer, Water Board",
            "what_you_should_do": "No action is required from you right now.",
            "next_step_label": "Repair",
            "then_step_label": "Citizen Verification",
        },
        "Repair": {
            "whats_happening": "The fault has been confirmed and repair or line-clearing work has been ordered.",
            "current_blocker": "Repair work is in progress.",
            "who_needs_to_act": "Water Board Maintenance Crew",
            "what_you_should_do": "No action is required from you right now.",
            "next_step_label": "Citizen Verification",
            "then_step_label": "Case Closed",
        },
        "Citizen Verification": {
            "whats_happening": "The authority has marked this as resolved. We're waiting for you to confirm supply is actually back to normal.",
            "current_blocker": "Your confirmation is the only remaining step.",
            "who_needs_to_act": "You",
            "what_you_should_do": "Check your water supply and tell us if it's actually normal now.",
            "next_step_label": "Case Closed",
            "then_step_label": "-",
        },
    },
    ServiceCategory.PF_CLAIM: {
        "Submitted": {
            "whats_happening": "Your PF claim has been received by EPFO.",
            "current_blocker": "Initial validation is pending.",
            "who_needs_to_act": "EPFO Claims Verification",
            "what_you_should_do": "No action is required from you right now.",
            "next_step_label": "Validated",
            "then_step_label": "Employer Verification",
        },
        "Validated": {
            "whats_happening": "Your claim has passed initial validation but is waiting for employer verification.",
            "current_blocker": "Employer verification has not been completed.",
            "who_needs_to_act": "Your employer / relevant verification authority",
            "what_you_should_do": "Contact your employer and request completion of verification.",
            "next_step_label": "Employer Verification",
            "then_step_label": "Approval",
        },
        "Employer Verification": {
            "whats_happening": "EPFO is waiting on your employer to confirm your service and contribution details.",
            "current_blocker": "Employer verification has not been completed.",
            "who_needs_to_act": "Your employer",
            "what_you_should_do": "Contact your employer and request completion of verification.",
            "next_step_label": "Approval",
            "then_step_label": "Payment",
        },
        "Approval": {
            "whats_happening": "Your claim has been verified and is awaiting final approval from a claims officer.",
            "current_blocker": "Final approval is pending.",
            "who_needs_to_act": "EPFO Claims Officer",
            "what_you_should_do": "No action is required from you right now.",
            "next_step_label": "Payment",
            "then_step_label": "Case Closed",
        },
        "Payment": {
            "whats_happening": "Your claim has been approved and payment has been initiated.",
            "current_blocker": "Bank credit is being processed.",
            "who_needs_to_act": "EPFO Payments Team",
            "what_you_should_do": "Check your bank account in the next few days.",
            "next_step_label": "Case Closed",
            "then_step_label": "-",
        },
    },
    ServiceCategory.PENSION: {
        "Submitted": {
            "whats_happening": "Your pension delay report has been received.",
            "current_blocker": "Verification against pension records is pending.",
            "who_needs_to_act": "Pension Department",
            "what_you_should_do": "No action is required from you right now.",
            "next_step_label": "Verified",
            "then_step_label": "Treasury Processing",
        },
        "Verified": {
            "whats_happening": "Your pension record has been verified and sent for treasury processing.",
            "current_blocker": "Treasury processing has not started.",
            "who_needs_to_act": "District Treasury",
            "what_you_should_do": "No action is required from you right now.",
            "next_step_label": "Treasury Processing",
            "then_step_label": "Bank Credit",
        },
        "Treasury Processing": {
            "whats_happening": "The treasury is processing your pending pension payment.",
            "current_blocker": "Payment has not yet been released by the treasury.",
            "who_needs_to_act": "District Treasury",
            "what_you_should_do": "No action is required from you right now, but this stage is worth escalating if it drags on.",
            "next_step_label": "Bank Credit",
            "then_step_label": "Citizen Verification",
        },
        "Bank Credit": {
            "whats_happening": "Payment has been released and should reflect in your bank account shortly.",
            "current_blocker": "Bank credit is being processed.",
            "who_needs_to_act": "Your bank",
            "what_you_should_do": "Check your bank account in the next few days.",
            "next_step_label": "Citizen Verification",
            "then_step_label": "Case Closed",
        },
        "Citizen Verification": {
            "whats_happening": "The authority has marked this as resolved. We're waiting for you to confirm the pension was actually credited.",
            "current_blocker": "Your confirmation is the only remaining step.",
            "who_needs_to_act": "You",
            "what_you_should_do": "Check your bank account and tell us if the pension actually arrived.",
            "next_step_label": "Case Closed",
            "then_step_label": "-",
        },
    },
    ServiceCategory.SCHOLARSHIP: {
        "Submitted": {
            "whats_happening": "Your scholarship payment issue has been received.",
            "current_blocker": "Verification of your application is pending.",
            "who_needs_to_act": "Scholarship Directorate",
            "what_you_should_do": "No action is required from you right now.",
            "next_step_label": "Verified",
            "then_step_label": "Sanctioned",
        },
        "Verified": {
            "whats_happening": "Your application has been verified and is awaiting sanction.",
            "current_blocker": "Sanction approval is pending.",
            "who_needs_to_act": "Scholarship Verification Officer",
            "what_you_should_do": "No action is required from you right now.",
            "next_step_label": "Sanctioned",
            "then_step_label": "Bank Credit",
        },
        "Sanctioned": {
            "whats_happening": "Your scholarship has been sanctioned and sent for payment.",
            "current_blocker": "Bank credit has not been processed yet.",
            "who_needs_to_act": "Scholarship Disbursement Cell",
            "what_you_should_do": "Double-check that your bank account details on file are correct.",
            "next_step_label": "Bank Credit",
            "then_step_label": "Citizen Verification",
        },
        "Bank Credit": {
            "whats_happening": "Payment has been released and should reflect in your bank account shortly.",
            "current_blocker": "Bank credit is being processed.",
            "who_needs_to_act": "Bank / Disbursement Cell",
            "what_you_should_do": "Check your bank account in the next few days.",
            "next_step_label": "Citizen Verification",
            "then_step_label": "Case Closed",
        },
        "Citizen Verification": {
            "whats_happening": "The authority has marked this as resolved. We're waiting for you to confirm the scholarship was actually credited.",
            "current_blocker": "Your confirmation is the only remaining step.",
            "who_needs_to_act": "You",
            "what_you_should_do": "Check your bank account and tell us if the amount actually arrived.",
            "next_step_label": "Case Closed",
            "then_step_label": "-",
        },
    },
    ServiceCategory.CERTIFICATE: {
        "Submitted": {
            "whats_happening": "Your application has been received.",
            "current_blocker": "Document verification has not started.",
            "who_needs_to_act": "Revenue Department",
            "what_you_should_do": "No action is required from you right now.",
            "next_step_label": "Document Verification",
            "then_step_label": "Field Verification",
        },
        "Document Verification": {
            "whats_happening": "Your submitted documents are being checked for completeness and accuracy.",
            "current_blocker": "Document verification is still pending.",
            "who_needs_to_act": "Revenue Inspector",
            "what_you_should_do": "No action is required from you right now.",
            "next_step_label": "Field Verification",
            "then_step_label": "Approval",
        },
        "Field Verification": {
            "whats_happening": "A field visit or local record check is required before approval.",
            "current_blocker": "Field verification has not been completed.",
            "who_needs_to_act": "Revenue Inspector",
            "what_you_should_do": "No action is required from you right now, but this stage is worth escalating if it drags on.",
            "next_step_label": "Approval",
            "then_step_label": "Certificate Issued",
        },
        "Approval": {
            "whats_happening": "Your application has passed verification and is awaiting sign-off.",
            "current_blocker": "Final approval is pending.",
            "who_needs_to_act": "Taluk Office",
            "what_you_should_do": "No action is required from you right now.",
            "next_step_label": "Certificate Issued",
            "then_step_label": "Case Closed",
        },
        "Certificate Issued": {
            "whats_happening": "Your certificate has been approved and issued.",
            "current_blocker": "Collection or download confirmation is pending.",
            "who_needs_to_act": "You",
            "what_you_should_do": "Collect or download your certificate and confirm you received it.",
            "next_step_label": "Case Closed",
            "then_step_label": "-",
        },
    },
    ServiceCategory.OTHER: {
        "Submitted": {
            "whats_happening": "Your report has been received and is being reviewed.",
            "current_blocker": "Assignment to the right team is pending.",
            "who_needs_to_act": "Municipal Grievance Cell",
            "what_you_should_do": "No action is required from you right now.",
            "next_step_label": "Assigned",
            "then_step_label": "Under Review",
        },
        "Assigned": {
            "whats_happening": "Your complaint has been assigned to a grievance officer.",
            "current_blocker": "Review has not started.",
            "who_needs_to_act": "Grievance Officer",
            "what_you_should_do": "No action is required from you right now.",
            "next_step_label": "Under Review",
            "then_step_label": "Action Taken",
        },
        "Under Review": {
            "whats_happening": "Your case is being reviewed to decide the right next step.",
            "current_blocker": "Review has not concluded.",
            "who_needs_to_act": "Grievance Officer",
            "what_you_should_do": "No action is required from you right now.",
            "next_step_label": "Action Taken",
            "then_step_label": "Citizen Verification",
        },
        "Action Taken": {
            "whats_happening": "Action has been taken on your case.",
            "current_blocker": "Confirmation that the action fully resolves the issue is pending.",
            "who_needs_to_act": "Grievance Officer",
            "what_you_should_do": "No action is required from you right now.",
            "next_step_label": "Citizen Verification",
            "then_step_label": "Case Closed",
        },
        "Citizen Verification": {
            "whats_happening": "The authority has marked this as resolved. We're waiting for you to confirm it's actually fixed.",
            "current_blocker": "Your confirmation is the only remaining step.",
            "who_needs_to_act": "You",
            "what_you_should_do": "Check the issue and tell us if it's actually resolved.",
            "next_step_label": "Case Closed",
            "then_step_label": "-",
        },
    },
}


def get_template(category: ServiceCategory, stage_name: str) -> dict[str, str]:
    category_templates = TEMPLATES.get(category, TEMPLATES[ServiceCategory.OTHER])
    return category_templates.get(stage_name, category_templates["Submitted"])
